spring:
  application:
    name: shaoxing-showcase-web-backend
  datasource:
    url: "jdbc:mysql://120.26.144.127:3306/HexWarrior6shaoxingshowcase?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
    username: "root"
    password: "Mzk2005123"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
